# Site settings
title: TurpleBlog
description: >
  A blog for me to practice my writing skills, and possibly captivate your
  attention!
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://turplepurtle.com" # the base hostname & protocol for your site
twitter_username: trplprtl
github_username:  TurplePurtle

# Build settings
markdown: kramdown
